version: '3.8'

services:
  backend-dev:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    environment:
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=8080
      - FRONTEND_URL=http://localhost:3000
      - GIN_MODE=debug
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - backend_modules:/go/pkg/mod
    networks:
      - app-network
    restart: unless-stopped
    command: ["air", "-c", ".air.toml"]

  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080
      - NEXT_PUBLIC_GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - NODE_ENV=development
    env_file:
      - ./frontend/.env.local
    volumes:
      - ./frontend:/app
      - frontend_modules:/app/node_modules
    networks:
      - app-network
    depends_on:
      - backend-dev
    restart: unless-stopped
    command: ["npm", "run", "dev"]

networks:
  app-network:
    driver: bridge

volumes:
  backend_modules:
  frontend_modules: